### ISSUE TITLE
missing feature 

### ISSUE THREAD

**Issue by walidar** [klinker-apps/pulse-sms-web#106] opened 2020-02-13 18:36 UTC
two SIMs support is missing. there should be a way to select the SIM to us when sending the SMS as in the android app.

**Comment by klinker24** [comment] 2020-02-13 21:21
Duplicate of https://github.com/klinker-apps/pulse-sms-issues/issues/649

We track features across all platforms, on that repo.

**Closed by klinker24** 2020-02-13 21:21 UTC
